---
title: "Short Vitae"
output:
  html_document:
    fig_width: 1
---


----

**Education**

**PhD in Economics**, Since 2019

Ecole d'Economie de la Sorbonne (UMR Développement & Sociétés), France


**Master in Development Economics**, 2019

Paris-1 Panthéon-Sorbonne University (IEDES), France


**Double degree in Economics and History**, 2017

Caen University, France

----

**Teaching**

**Graduate Assistant (ATER)** in Development Economics (master level)

Paris-1 Panthéon-Sorbonne University (IEDES), 2022-2023

- Measurement (Labor and Employment in Developing Countries) - M1

- Quantitative Methods training course - M1

- Data and Climate (an Introduction to R and an education on data and the construction of sustainable development indicators.) - M2

- Applied Econometrics - M1

- Tutored Projects in development economics - M1


**Lecturer** in Collection and analysis of quantitative and qualitative data (master level)

Paris-1 Panthéon-Sorbonne University & UFTAM (L'Université franco-tunisienne pour l'Afrique et la Méditerranée), 2022


**Assistant Lecturer** in Econometrics (undergraduate level)

Paris-1 Panthéon-Sorbonne University, 2021


**Teaching Assistant** in microeconomics, macroeconomics and inferential statistics (undergraduate level)

Caen University, 2017


----

[Curriculum Vitae](https://jeanbaptisteguiffard.github.io/mywebsite/CV_JBG_univ_20042023.pdf)
