---
name: Jean-Baptiste
surname: Guiffard
position: "PhD Candidate"
address: "IEDES/UMR D&S, Université Paris-1 Panthéon-Sorbonne, 45 bis Avenue de la Belle Gabrielle, 94130, Nogent-sur-Marne, France"
phone: +33 6 87 96 61 05
www: https://jeanbaptisteguiffard.github.io/
email: "jean-baptiste.guiffard@univ-paris1.fr"
twitter: https://twitter.com/JBGuiffard
github: https://github.com/jeanbaptisteguiffard
linkedin: https://www.linkedin.com/in/jean-baptiste-guiffard-b7063090/
date: "`r format(Sys.time(), '%B %Y')`"
output:
  vitae::awesomecv:
    page_total: true
---





```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Informal studies", "1889-91", "Flying University", "Warsaw, Poland",
  "Master of Physics", "1893", "Sorbonne Université", "Paris, France",
  "Master of Mathematics", "1894", "Sorbonne Université", "Paris, France"
) %>%
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>%
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year,
    Desc
  )
```

# Publications

